const searchEngineList = [
    {
        'name': 'google',
        'url': 'https://www.google.com/search?newwindow=1&q=',
        'href': 'https://www.google.com/'
    }, {
        'name': 'googlehk',
        'url': 'https://www.google.com.hk/search?q=',
        'href': 'https://www.google.com.hk/'
    }, {
        'name': 'baidu',
        'url': 'https://www.baidu.com/s?wd=',
        'href': 'https://www.baidu.com/'
    }, {
        'name': 'MDN',
        'url': 'https://developer.mozilla.org/zh-CN/search?q=',
        'href': 'https://developer.mozilla.org/zh-CN/'
    }, {
        'name': 'bilibili',
        'url': 'http://search.bilibili.com/all?keyword=',
        'href': 'http://search.bilibili.com/'
    }, {
        'name': 'xianyu',
        'url': 'https://s.2.taobao.com/list/list.htm?q=',
        'href': 'https://2.taobao.com/'
    }, {
        'name': 'github',
        'url': 'https://github.com/search?utf8=%E2%9C%93&q=',
        'href': 'https://github.com/'
    }, {
        'name': '谷歌翻译',
        'url': 'http://translate.google.cn/#en/zh-CN/',
        'href': 'https://translate.google.cn/'
    }, {
        'name': 'steam',
        'url': 'http://store.steampowered.com/search/?&term=',
        'href': 'http://store.steampowered.com/'
    }, {
        'name': 'steaminfo',
        'url': 'https://steamdb.info/search/?a=app&q=',
        'href': 'https://steamdb.info/'
    }, {
        'name': 'findicons',
        'url': 'http://findicons.com/search/',
        'href': 'http://findicons.com/'
    }, {
        'name': 'konachan',
        'url': 'http://konachan.net/post?tags=',
        'href': 'http://konachan.net/'
    }, {
        'name': 'pixiv',
        'url': 'http://www.pixiv.net/search.php?s_mode=s_tag&word=',
        'href': ' http://www.pixiv.net'
    }, {
        'name': 'pixivid',
        'url': 'http://www.pixiv.net/member_illust.php?mode=medium&illust_id=',
        'href': ' http://www.pixiv.net'
    }, {
        'name': 'pixiv18',
        'url': 'http://www.pixiv.net/search.php?s_mode=s_tag&r18=1&word=',
        'href': ' http://www.pixiv.net'
    }, {
        'name': 'npmjs',
        'url': 'https://www.npmjs.com/package/',
        'href': 'https://www.npmjs.com/package/package'
    }, {
        'name': '谷歌镜像',
        'url': 'http://soguge.com/search?hl=zh-CN&q=',
        'href': 'http://www.google.com/'
    }, {
        'name': 'bing',
        'url': 'http://global.bing.com/search?q=',
        'href': 'http://global.bing.com/'
    }, {
        'name': '必应',
        'url': 'http://cn.bing.com/search?q=',
        'href': 'http://cn.bing.com/'
    }, {
        'name': 'yahoo!',
        'url': 'https://sg.search.yahoo.com/search?p=',
        'href': 'https://search.yahoo.com/'
    }, {
        'name': '网易云音乐',
        'url': 'http://music.163.com/#/search/m/?s=',
        'href': 'http://music.163.com/#'
    }, {
        'name': '维基百科',
        'url': 'https://zh.wikipedia.org/w/index.php?search=',
        'href': 'https://zh.wikipedia.org/wiki/Wikipedia:首页'
    }, {
        'name': 'wikipedia',
        'url': 'https://en.wikipedia.org/wiki/',
        'href': 'https://www.wikipedia.org/'
    }, {
        'name': '谷歌搜图',
        'url': 'https://www.google.com.hk/search?newwindow=1&safe=strict&hl=zh-CN&site=webhp&tbm=isch&sa=1&q=',
        'href': 'https://www.google.com/'
    }, {
        'name': '百度搜图',
        'url': 'http://image.baidu.com/search/index?tn=baiduimage&ps=1&ct=201326592&lm=-1&cl=2&nc=1&ie=utf-8&word=',
        'href': 'https://www.baidu.com/'
    }, {
        'name': 'torrentkitty',
        'url': 'https://www.torrentkitty.tv/search/',
        'href': 'https://www.torrentkitty.tv/'
    }, {
        'name': '虾米音乐',
        'url': 'http://www.xiami.com/search?key=',
        'href': 'http://www.xiami.com/'
    }, {
        'name': '高德地图',
        'url': 'http://ditu.amap.com/search?query=',
        'href': 'http://ditu.amap.com/'
    }, {
        'name': '百度云',
        'url': 'http://baiduyun.57fx.cn/so-result.html?keyword=',
        'href': 'https://pan.baidu.com/disk/home#list/path=%2F'
    }
];

export default searchEngineList;
