const websites = [
    {
        ACG: {
            bilibili: 'http://www.bilibili.com',
            niconico: 'http://www.nicovideo.jp/',
            u2b: 'https://www.youtube.com/',
            tumblr: 'https://www.tumblr.com/',
            u2bdl: 'https://youtubemultidownloader.com/',
            steam: 'http://store.steampowered.com/',
            steamCN: 'https://steamcn.com/forum.php',
            bangumi: 'http://bangumi.tv/',
            acfun: 'http://www.acfun.tv/',
            thwiki: 'http://www.thwiki.cc/',
            pixiv: 'http://www.pixiv.net/',
            hpoi: 'http://www.hpoi.net/',
            saucenao: 'http://saucenao.com/',
            iqdb: 'http://iqdb.org/',
            safebooru: 'http://safebooru.org/',
            tineye: 'https://www.tineye.com/',
            Tbus: 'http://games.tgbus.com/pspcn/',
            dilidili: 'http://www.dilidili.wang/',
            osu: 'https://osu.ppy.sh/home',
            sankakucomplex: 'https://chan.sankakucomplex.com/',
            hacg: 'https://www.llss.fun/',
            steamcard: 'http://www.steamcardexchange.net/'
        },
        SNS: {
            weibo: 'http://weibo.com/',
            zhihu: 'https://www.zhihu.com/',
            wx: 'https://wx.qq.com/',
            t66y: 'https://t66y.com/index.php',
            quora: 'https://www.quora.com/#',
            douban: 'https://www.douban.com/',
            twitter: 'https://twitter.com/',
            linkedin: 'https://www.linkedin.com/',
            weixin: 'https://wx.qq.com/',
            V2EX: 'https://www.v2ex.com/'
        },
        Techonology: {
            github: 'https://github.com/love999262',
            gitbooks: 'https://www.gitbook.com/',
            imooc: 'http://www.imooc.com',
            study163: 'http://study.163.com/',
            bandwagon: 'https://bwh1.net/',
            stackoverflow: 'http://stackoverflow.com/',
            typescript: 'https://www.typescriptlang.org/',
            tscn: 'https://www.tslang.cn/',
            w3schools: 'http://www.w3schools.com/',
            '$.api': 'http://api.jquery.com/',
            jshint: 'http://jshint.com/',
            jsfiddle: 'https://jsfiddle.net/',
            caniuse: 'http://caniuse.com/',
            jsonlint: 'https://jsonlint.com/',
            babel: 'http://babeljs.io/',
            nodejscn: 'http://nodejs.cn/',
            vue: 'http://cn.vuejs.org/v2/api/',
            webpackCN: 'https://doc.webpack-china.org/',
            webpackDoc: 'http://webpack.github.io/docs/',
            ReactCN: 'https://doc.react-china.org/',
            React: 'https://facebook.github.io/react/',
            pythonDoc: 'https://docs.python.org/3/',
            owasp: 'https://www.owasp.org'
        },
        Shopping: {
            taobao: 'https://www.taobao.com/',
            JD: 'http://www.jd.com/',
            Amazon: 'http://www.amazon.cn/',
            smzdm: 'http://www.smzdm.com/',
            moebuy: 'http://www.030buy.net/',
            AmazonJP: 'https://www.amazon.co.jp/'
        },
        English: {
            bbc: 'http://www.bbc.co.uk/',
            voa: 'http://www.voa.com/',
            usatoday: 'http://www.usatoday.com/',
            latimes: 'http://www.latimes.com/',
            nytimes: 'http://www.nytimes.com/',
            washingtonpost: 'http://www.washingtonpost.com/',
            wsj: 'http://www.wsj.com/',
            nydailynews: 'http://www.nydailynews.com/',
            reddit: 'https://www.reddit.com/',
            imdb: 'http://www.imdb.com/',
            nypost: 'http://www.nypost.com/'
        },
        Others: {
            exmail: 'https://exmail.qq.com/',
            hotmail: 'https://outlook.live.com/owa/',
            xvcams: 'http://xvcams.com',
            icloud: 'https://www.icloud.com',
            myfreecams: 'https://www.myfreecams.com/',
            gmail: 'https://mail.google.com/mail/u/0/#inbox',
            'iconfont.cn': 'http://www.iconfont.cn/',
            tinypng: 'https://tinypng.com/',
            giphy: 'http://giphy.com/',
            alexa: 'http://www.alexa.com/',
            qiniu: 'https://portal.qiniu.com/'
        }
    }
];

export default websites;
